<Project>
  <!-- Import parent Directory.build.props -->
  <Import Project="../Directory.Build.props" />

  <PropertyGroup>
    <PlatformTarget Condition="'$(PlatformTarget)' == '' or '$(PlatformTarget)' == 'AnyCPU'">x86</PlatformTarget>
    <BaseIntermediateOutputPath>obj/$(PlatformTarget)/</BaseIntermediateOutputPath>
  </PropertyGroup>
</Project>